name: Add issues to projects

on:
  workflow_call:

jobs:
  add-triage-label:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'issues' }}
    steps:
      - name: Add 'triage' label to Issue
        uses: octokit/request-action@v2.1.4
        with:
          route: POST /repos/{owner}/{repo}/issues/{issue_number}/labels
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.issue.number }}
          body: '{"labels":"triage"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  add-to-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub Projects
        uses: actions/add-to-project@v0.0.3
        with:
          project-url: https://github.com/orgs/yamigo-be/projects/7
          github-token: ${{ secrets.GH_PROJECTS_PAT }}
