name: Add issues to projects

on:
  workflow_call:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub Projects
        uses: actions/add-to-project@v0.0.3
        with:
          project-url: https://github.com/orgs/yamigo-be/projects/7
          github-token: ${{ secrets.GH_PROJECTS_PAT }}
